export const GET_BLOGS_LIST="GET_BLOGS_LIST";
export const BLOGS_LIST_RECIEVE="BLOGS_LIST_RECIEVE";
export const ADD_BLOG="ADD_BLOG";
export const EDIT_BLOG="EDIT_BLOG";
export const DELETE_BLOG="DELETE_BLOG";

